### ISSUE TITLE
Typo in random number request.

### ISSUE THREAD

**Issue by mcpiatkowski** [smartcontractkit/apeworx-starter-kit#10]
Hello. First of all thanks for a great starter. That really boosts a progress for a beginner.

I have just found little typo. We miss "F" in the snippet below in [request_and_read_randomness.py](https://github.com/smartcontractkit/apeworx-starter-kit/blob/main/scripts/request_and_read_randomness.py).

`vrf_consumer = project.VRConsumerV2.deployments[-1]`

After correcting it works like a charm.

**Comment by andrejrakic** [comment]
Thanks for raising this issue @mcpiatkowski, fixed in #11 (thanks @rgottleber)
