### ISSUE TITLE
AttributeError: 'ProjectManager' object has no attribute 'MockV3Aggregator'

### ISSUE THREAD

**Issue by Luca-Blight** [smartcontractkit/apeworx-starter-kit#5]
Running across the error below when attempting to deploy contracts.

apeworx-starter-kit/lib/python3.9/site-packages/ape/managers/project/manager.py 
line 292, in __getattr__ return self.__getattribute__(attr_name)  # type: ignore
AttributeError: 'ProjectManager' object has no attribute 'MockV3Aggregator'

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue!

Could you please tell me exactly step-by-step how you got this issue starting with

```
git clone https://github.com/smartcontractkit/apeworx-starter-kit
```

**Comment by Luca-Blight** [comment]
It was a peculiar pathing issue I created by accident. This can be closed.
